/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../Include/Animation.c"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define MODULES_COUNT    4
#define WIDTH           32
#define HEIGHT           8

#define MAX(a, b) ((a) > (b) ? (a) : (b))

typedef struct {
	 volatile uint32_t MODER;
	 volatile uint32_t OTYPER;
	 volatile uint32_t OSPEEDR;
	 volatile uint32_t PUPDR;
	 volatile uint32_t IDR;
	 volatile uint32_t ODR;
	 volatile uint32_t BSSR;
	 volatile uint32_t r0;
	 volatile uint32_t AFRL;
	 volatile uint32_t AFRH;
} GPIO_Typedef;

#define GPIOA ((GPIO_Typedef*)0x40020000)

typedef struct {
	volatile uint32_t CR1;
	volatile uint32_t r[2];
	volatile uint32_t DIER;
	volatile uint32_t SR;
	volatile uint32_t EGR;
	volatile uint32_t CCMR1;
	volatile uint32_t CCMR2;
	volatile uint32_t CCER;
	volatile uint32_t CNT;
	volatile uint32_t PSC;
	volatile uint32_t ARR;
	volatile uint32_t r2;
	volatile uint32_t CCR1;
	volatile uint32_t CCR2;
} TIM_Typedef;

#define TIM2 ((TIM_Typedef*)0x40000000)

typedef struct {
	 volatile uint32_t CR;
	 volatile uint32_t PLLCFGR;
	 volatile uint32_t CFGR;
	 volatile uint32_t reserved0[9];
	 volatile uint32_t AHB1ENR;
	 volatile uint32_t AHB2ENR;
	 volatile uint32_t AHB3ENR;
	 volatile uint32_t reserved1;
	 volatile uint32_t APB1ENR;
	 volatile uint32_t APB2ENR;
} RCC_Typedef;

#define RCC ((RCC_Typedef*)0x40023800)

typedef struct {
	volatile uint32_t CR1;
	volatile uint32_t CR2;
	volatile uint32_t SR;
	volatile uint32_t DR;
	volatile uint32_t CRCPR;
	volatile uint32_t RXCRCR;
	volatile uint32_t TXCRCR;
} SPI_Typedef;

#define SPI1 ((SPI_Typedef*)0x40013000)

typedef struct {
	volatile uint32_t ISER0[7];
} NVIC_Typedef;

#define NVIC ((NVIC_Typedef*)0xE000E100)

volatile uint8_t count = 0;
volatile uint8_t ticks = 0;
void timer_init() {
	TIM2->PSC = 1023;
	TIM2->ARR =  15623;

	TIM2->DIER |= (1 << 0);
	TIM2->CR1 |= (1 << 0);

	NVIC->ISER0[0] |= (1 << 28);
}

void TIM2_IRQHandler(void) {
	if(TIM2->SR &(1 << 0)) {
		TIM2->SR &= ~(1 << 0);
		count++;
	}
}

void init(void) {
	RCC->AHB1ENR |= (1 << 0);
	RCC->APB1ENR |= (1 << 0);
	RCC->APB2ENR |= (1 << 12);

	GPIOA->MODER &= ~(3 << (7 * 2));
	GPIOA->MODER &= ~(3 << (5 * 2));
	GPIOA->MODER &= ~(3 << (4 * 2));
	GPIOA->MODER |= (2 << (7 * 2)) | (2 << (5 * 2));
	GPIOA->MODER |=  (1 << (4 * 2));

	GPIOA->MODER &= ~(3 << (8 * 2));

	GPIOA->AFRL &= ~(0xF << (7 * 4));
	GPIOA->AFRL &= ~(0xF << (5 * 4));
	GPIOA->AFRL |= (5 << (7 * 4)) | (5 << (5 * 4));
	GPIOA->BSSR = (1 << 4);

	SPI1->CR1 |= (1 << 14);
	SPI1->CR1 |= (1 << 15);
	SPI1->CR1 &= ~(1 << 0);
	SPI1->CR1 &= ~(1 << 1);

	SPI1->CR1 |= (1 << 11);

	SPI1->CR1 &= ~(0b111 << 3);
	SPI1->CR1 |= (0b111 << 3);

	SPI1->CR1 |= (1 << 9);
	SPI1->CR1 |= (1 << 8);

	SPI1->CR1 |= (1 << 2);

	SPI1->CR1 |= (1 << 6);

}

void send2Bytes(uint16_t halfword) {
	while(!(SPI1->SR & (1 << 1)));
	SPI1->DR = halfword;
}

void led_on_chained(uint8_t m, uint16_t pos) {

	GPIOA->BSSR = (1 << (4 + 16));

	for(int i = 3; i >= 0; i--) {
		send2Bytes(i == m ? pos : 0x0000);
	}
	while(SPI1->SR & (1 << 7));
	GPIOA->BSSR = (1 << 4);
}

void stop_animation(void) {
	for (uint8_t row = 1; row <= 8; row++) {
	        for (uint8_t m = 0; m < 4; m++) {
	            led_on_chained(m, (row << 8) | 0x00); // Send blank byte to row
	        }
	    }

}

void test_animation(Animation ani) {
	if(count == 1) {
		for(volatile uint8_t i = 0; i <= (ani.num_animations - 1); i++) {
			led_on_chained(0,ani.animation[i].frames[ticks]);
			led_on_chained(0,ani.animation[i].frames[ticks]);
			led_on_chained(0,ani.animation[i].frames[ticks]);
		}

		ticks++;
		count = 0;
		if(ticks >= ani.animation[1].num_frames) {
			for(volatile uint32_t i = 0; i < 500000; i++);
			stop_animation();
			ticks = 0;
		}
	}
}

void set_intensity(uint8_t i) {
	volatile uint16_t pos = 0x0A00;
	pos |= i;

	for(volatile uint8_t m = 0; m < 4; m++) {
		led_on_chained(m, i);
	}
}

uint32_t rng_state = 123456789;
uint32_t software_rand(void) {
    rng_state = rng_state * 1103515245 + 12345;
    return rng_state & 0x7FFFFFFF;
}

int drops[WIDTH];
void matrix_rain(void) {
    for (int col = 0; col < WIDTH; col++) {
        drops[col]++;

        if (drops[col] >= HEIGHT) {
            drops[col] = -(int)(software_rand() % 16);
        }
    }

    for (int m = 0; m < MODULES_COUNT; m++) {

        for (int reg_index = 0; reg_index < 8; reg_index++) {

            int global_col = (m * 8) + reg_index;
            int active_row = drops[global_col];

            uint8_t mask = 0x00;
            if (active_row >= 0 && active_row < HEIGHT) {
                mask = (1 << active_row);
            }

            uint8_t reg_address = reg_index + 1;
            uint16_t pos = (reg_address << 8) | mask;

            led_on_chained(m, pos);
        }
    }

    for (volatile uint32_t i = 0; i < 25000; i++);
}

uint8_t fire_matrix[256];
void update_fire(void) {
	for(int i = 0; i < WIDTH; i++) {
		int bottom_index = ((HEIGHT - 1) * WIDTH) + i;
		fire_matrix[bottom_index] = 4;
	}

	for(int i = 1; i < HEIGHT; i++){
		for(int j = 0; j < WIDTH; j++) {
			int idx = (i * WIDTH) + j;
			int heat = fire_matrix[idx];

			if(heat > 0) {
				uint8_t decay;
				if(software_rand() < 1395864370) {
					decay = 1;
				}
				else {
					decay = 0;
				}

				int new_heat = MAX(0,heat-decay);

				int wind = (software_rand() % 3) - 1;

				int d_x = (j + wind) % WIDTH;

				 if (d_x < 0) d_x = WIDTH - 1;
				 else if (d_x >= WIDTH) d_x = 0;

				int d_y = i - 1;
				int d_idx = (d_y * WIDTH) + d_x;

				fire_matrix[d_idx] = new_heat;
			}

		}
	}
}

void diplay_fire(void) {
    for (uint8_t row_reg = 1; row_reg <= 8; ++row_reg) {
        uint8_t y = row_reg - 1;


        GPIOA->BSSR = (1 << (4 + 16));

        for (int8_t module = 3; module >= 0; --module) {
            uint8_t module_byte = 0x00;
            uint8_t start_x = module * 8;

            for (uint8_t bit_pos = 0; bit_pos < 8; ++bit_pos) {
                uint8_t x = start_x + bit_pos;
                uint8_t heat_val = fire_matrix[(y * WIDTH) + x];

                uint8_t is_on = 0;
                if (heat_val >= 2) {
                    is_on = 1;
                } else if (heat_val == 1) {
                    if (software_rand() < 858993459) {
                        is_on = 1;
                    }
                }

                if (is_on) {
                    module_byte |= (1 << (7 - bit_pos));
                }
            }

            uint16_t packet = (row_reg << 8) | module_byte;

            send2Bytes(packet);
        }

        while(SPI1->SR & (1 << 7));

        GPIOA->BSSR = (1 << 4);
    }
}

void flame_animation() {
	update_fire();
	display_fire();
	for (volatile uint32_t i = 0; i < 155000; i++) { asm("nop"); };
}

int main(void)
{
	init();
	timer_init();
	for (uint8_t m = 0; m < 4; m++) {
	      led_on_chained(m, 0x0F00);
	      led_on_chained(m, 0x0C01);
	      led_on_chained(m, 0x0900);
	      led_on_chained(m, 0x0B07);
	      led_on_chained(m, 0x0A05);
	  }

	stop_animation();
	while(1) {
		//matrix_rain();

    }
}
